# Generated by Django 3.0.2 on 2020-03-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_join_team_project_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join_team',
            old_name='username',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='join_team',
            old_name='Professor_id',
            new_name='to_user',
        ),
    ]
